version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "chore(pip)"
    groups:
      python-deps:
        patterns:
          - "*"
    assignees:
      - "Ayman-Abdulgalil"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    commit-message:
      prefix: "chore(npm)"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "@eslint/js"
    groups:
      npm-deps:
        patterns:
          - "*"
    assignees:
      - "omojoimadi"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(docker)"
    groups:
      docker-deps:
        patterns:
          - "*"
    assignees:
      - "Ayman-Abdulgalil"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(docker-backend)"
    groups:
      docker-backend-deps:
        patterns:
          - "*"
    assignees:
      - "Ayman-Abdulgalil"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(docker-frontend)"
    groups:
      docker-frontend-deps:
        patterns:
          - "*"
    assignees:
      - "omojoimadi"
    reviewers:
      - "Ayman-Abdulgalil"
